node:
  image: trufflesuite/ganache-cli:latest
  ports:
    - "8545:8545"
  volumes:
    - ./ganache_data:/ganache_data
  entrypoint:
    - node
    - ./build/cli.node.js
    - --deterministic
    - --db=/ganache_data
    - --mnemonic
    - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
    - --networkId
    - '5777'
    - --hostname
    - '0.0.0.0'
    - --debug
    - --verbose
# ENTRYPOINT ["node", "./build/cli.node.js"]

